# Generated by Django 2.1.5 on 2019-02-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='address',
            new_name='url',
        ),
    ]
