# Generated by Django 2.1.5 on 2019-06-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='status',
        ),
        migrations.AddField(
            model_name='settings',
            name='installstatus',
            field=models.BooleanField(default=False),
        ),
    ]
