# Generated by Django 2.1.5 on 2019-06-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0002_auto_20190602_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='serverip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
