# Generated by Django 2.1.5 on 2019-05-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=200, unique=True)),
                ('caddy_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('dns_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.DNS')),
            ],
        ),
    ]
