# Generated by Django 2.1.5 on 2019-02-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.URLField()),
                ('tls', models.BooleanField(default=True)),
                ('staging', models.BooleanField(default=False)),
            ],
        ),
    ]
