# Generated by Django 2.1.5 on 2019-02-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
    ]
