# Generated by Django 2.1.5 on 2019-05-20 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0001_initial'),
        ('addresses', '0005_auto_20190513_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='dns_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dns.DNS'),
        ),
    ]
