#!/bin/sh
set -ex
set -u
set -o pipefail

################################################################################
# Compile the caddy webserver.
################################################################################

finish() {
  readonly RC=$?

  if [ ${RC} -eq 0 ]; then
    echo "$0" OK >&2
  else
    echo "$0" failed with exit code ${RC} >&2
    exit ${RC}
  fi
}

trap finish EXIT

# https://github.com/niemeyer/gopkg/issues/50
git config --global http.https://gopkg.in.followRedirects true

cd main/

# Fetch dependencies.
go get -d ./...

# Build!
mkdir /home/developer/bin
go build -o /home/developer/bin/caddy

# http://www.thegeekstuff.com/2012/09/strip-command-examples/
strip --strip-all /home/developer/bin/caddy